sonar.projectKey=ravindu200232_food-ordering-notification-service
sonar.organization=ravindu200232
sonar.projectName=Food Ordering - Notification Service
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/coverage/**,**/Dockerfile,**/*.md

sonar.tests=__tests__
sonar.test.inclusions=**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.language=js


# Do not block CI pipeline on Quality Gate result — gate is reviewed separately
sonar.qualitygate.wait=false