name: client CI
'on':
  push:
    branches:
    - main
    paths:
    - client/**
    - .github/workflows/client.yml
  pull_request:
    branches:
    - main
    paths:
    - client/**
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      working-directory: ./client
      run: npm ci || npm install
    - name: Build app
      working-directory: ./client
      run: npm run build
    - name: Build Docker image
      working-directory: ./client
      run: docker build -t local/${{ github.event.repository.name }}-client:${{ github.sha
        }} .
